-- CreateTable
CREATE TABLE "Item" (
    "sale_item_id" TEXT NOT NULL,
    "order_date" TIMESTAMP(3) NOT NULL,
    "payment_state" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "sku" TEXT,
    "sub_total" DECIMAL(65,30) NOT NULL,
    "package_id" TEXT NOT NULL,
    "ship_date" TIMESTAMP(3),
    "payment_id" TEXT NOT NULL,
    "tax" DECIMAL(65,30),
    "paypal_id" TEXT,
    "ship_notes" TEXT,
    "currency" TEXT,
    "order_total" DECIMAL(65,30) NOT NULL,
    "shipping" DECIMAL(65,30),
    "item_url" TEXT,
    "item_name" TEXT NOT NULL,
    "option" TEXT,
    "option_id" TEXT,
    "selling_band_url" TEXT,
    "ship_from_country_name" TEXT,
    "artist" TEXT NOT NULL,
    "discount_code" TEXT,
    "buyer_name" TEXT,
    "buyer_email" TEXT,
    "buyer_phone" TEXT,
    "buyer_note" TEXT,
    "ship_to_name" TEXT,
    "ship_to_street" TEXT,
    "ship_to_street_2" TEXT,
    "ship_to_city" TEXT,
    "ship_to_state" TEXT,
    "ship_to_zip" TEXT,
    "ship_to_country" TEXT,
    "ship_to_country_code" TEXT,

    CONSTRAINT "Item_pkey" PRIMARY KEY ("sale_item_id")
);
